### ISSUE TITLE
conf-pkg-config missing pkg-config command

### ISSUE THREAD

**Issue by ajbt200128** [balsoft/opam-nix#109]
**Describe the bug**
when building conf-pkg-config, we get
`> /nix/store/m1qnbq0pwlsbggjwwxwbq93ni8ila0gr-stdenv-darwin/setup: line 1737: pkg-config: command not found`

**Expected behavior**
Successful build

The following fixes this issue:
```
    conf-pkg-config = prev.conf-pkg-config.overrideAttrs (prev: {
      # We need to add the pkg-config path to the PATH so that dune can find it
      nativeBuildInputs = prev.nativeBuildInputs ++ [ pkgs.pkg-config ];
    });
```

**Comment by balsoft** [comment]
Thanks. Should be fixed now.

**Comment by ajbt200128** [comment]
Sorry, gave you the wrong fix, I think we actually want `pkgconf` https://github.com/ocaml/opam-repository/blob/master/packages/conf-pkg-config/conf-pkg-config.3/opam as this error is still occurring, but now says:
`> /nix/store/m1qnbq0pwlsbggjwwxwbq93ni8ila0gr-stdenv-darwin/setup: line 1741: pkgconf: command not found`

**Comment by balsoft** [comment]
Hm, I didn't realise `pkgconf` and `pkg-config` were separate things; I'll take a look.

**Comment by balsoft** [comment]
Interesting. I can do `nix build github:tweag/opam-nix#conf-pkg-config.3` on an aarch64-darwin machine and it builds, providing `pkg-config-wrapped` in its `propagated-build-inputs`. Are you on `x86_64-darwin` ?

**Comment by balsoft** [comment]
Aha, I think I see the problem. `pkgconf` is a drop-in-ish replacement for `pkg-config`, however the `pkgconf` package in nixpkgs doesn't provide a `pkg-config` binary (yet?). Meanwhile, the `conf-pkg-config` package in opam-repository requires `pkgconf` for darwin + homebrew, but tries to run `pkg-config --version` as the "build script". With `pkgconf` from nixpkgs, this obviously fails. However, just replacing `pkgconf` with `pkg-config` for now should resolve this, unless some dependencies do actually call `pkgconf` instead of `pkg-config`, and I don't see any such cases in the current version of `opam-repository`.

Can you tell me what rev of `opam-nix` you're using, what package fails, and ideally give me the flake you're working with?

**Comment by ajbt200128** [comment]
Thanks for looking into this, `nix build github:tweag/opam-nix#conf-pkg-config.3` works for me too.

flake is [here](https://github.com/semgrep/semgrep/blob/develop/flake.nix), we substitute in a newer version of the opam-repository, and update that at a weekly cadence, since we often update dependencies very quickly. If you check out semgrep.nix in the same repo you can see where we have an overlay to fix conf-pkg-config.

It looks like indeed it's because we're using a newer version of the opam-repository, that has conf-pkg-config.4 [here](https://github.com/ocaml/opam-repository/blob/a12dee6bc474c1adf530d0db26271d7b002230ff/packages/conf-pkg-config/conf-pkg-config.4/opam), and it uses pkgconf as the command for the homebrew distribution!

**Comment by balsoft** [comment]
Should be fixed for good now.

**Comment by ajbt200128** [comment]
will check it out, thanks!
