### ISSUE TITLE
Materialization does not work with local projects and pin-depends.

### ISSUE THREAD

**Issue by rizo** [balsoft/opam-nix#6]
**Description**
Currently `materialize` and `materializedDefsToScope` do not support working with local projects and thus cannot capture pinned dependencies. It would be great if there was a way to get a fully "locked" version of the project with resolved package versions and necessary URLs to be later loaded and built.

**Expected behavior**
Ideally, a common workflow present in other tools as [mentioned](https://github.com/tweag/opam-nix/issues/1#issuecomment-1019100450) by @brendanzab, would fit this use case. Specifically:

- lock:
  - load project's opam file(s);
  - solve dependency versions (including pinned packages);
  - create a lock file with the solution containing URLs and hashes;
- build:
  - fetch sources included in the lock file;
  - build the dependencies and the project.

I realise this is potentially significantly different to what opam-nix does presently. Could you share some details on the rationale behind the current design? I'd be happy to discuss alternative approaches, if you think this doesn't make sense.

An interesting project to look at for inspiration is opam-monorepo, which generates reproducible lock-files like: https://github.com/ocamllabs/opam-monorepo/blob/main/opam-monorepo.opam.locked.

**Comment by balsoft** [comment]
>  Currently materialize and materializedDefsToScope do not support working with local projects

They do. See `-l` flag to `opam-nix-gen` and `sourceMap` argument to `materializedDefsToScope`. An example: https://github.com/tweag/opam-nix#user-content-my-package-materialized and https://github.com/tweag/opam-nix/blob/main/examples/readme/my-package/package-defs.json. TL;DR: 

Run

```
opam-nix-gen -l . -p my-package > package-defs.json
```

Then in your flake, 

```
(materializedDefsToScope { sourceMap.my-package = ./.; } ./package-defs.json).my-package
```

It is true however that `materializedDefsToScope` does not support pin-depends yet.

>  Could you share some details on the rationale behind the current design?

The idea was to avoid generated files at all costs. Materialization support is entirely optional and all the features of opam-nix can be used without it. This is really important for me: to be able to use the tool without committing any extra file to the repository.

> I'd be happy to discuss alternative approaches

I think the best approach for now is to just make `materialize` resolve all the `pin-depends` to `git+https://<url>#<sha1>` form (or maybe even `{ url = ...; rev = ...; sha256 = ...; }` so that it can be downloaded with `fetchgit`), and then resolve `pin-depends` correctly in `materializedDefsToScope`.

**Comment by rizo** [comment]
> They do.

@balsoft Yes, sorry, I should have been more clear: I did test the script, but realised it doesn't support pin-depends.

I also tried creating a version of `materialize` called `materializeProject` that creates repos for the project and the pins before generating the JSON file, but as you mentioned, it needs more work to fetch sources during `materializedDefsToScope`.


> The idea was to avoid generated files at all costs. Materialization support is entirely optional and all the features of opam-nix can be used without it. This is really important for me: to be able to use the tool without committing any extra file to the repository.

That's an interesting requirement. I think it's really nice that opam-nix attempts to support both workflows. For my use-case having a lock file would help with reproducibility and would significantly improve build times (avoiding repo re-computation).

**Comment by balsoft** [comment]
Hey, there's now `materalizeOpamProject` which is an "intersection" of `buildOpamProject` and `materialize`. It fetches pin-depends and stores their "locked" versions in the `package-defs.json` it produces. And `materializedDefsToScope` now fetches those locked versions. Could you check if it works for you?

**Comment by balsoft** [comment]
`opam-nix-gen` now also supports `materializeOpamProject`. See the README example again.

**Comment by rizo** [comment]
Thanks for working on this, @balsoft!

I'm running into the following issues when running `opam-nix-gen`:

```
$ opam-nix-gen
Must supply at least one package (-p) option or project NAME and DIRECTORY as positional arguments
opam-nix-gen: Resolve opam packages and produce a JSON file suitable for consumption by materializedDefsToScope
Usage: opam-nix-gen [-r <REPO-URL> ...] [-l <DIRECTORY> ...] [-e VAR=VALUE ...] [-p NAME[.VERSION] ...] <-p NAME[.VERSION] | NAME DIRECTORY>
  Options:
    -r: Add a remote repository to the resolver context
    -l: Add a repository made from a local directory to the resolver context
    -e: Add an opam environment binding to the resolver context
    -p: Add a package to the resolver context
  (optional) Positional arguments:
    NAME: project's name
    DIRECTORY: project's directory
  (note: the project's directory must contain <NAME>.opam file)
  Examples:
/nix/store/xl7vdrxipggh2v5v2w5002l3rmzajzvp-opam-nix-gen/bin/opam-nix-gen: line 21: my-package: command not found
/nix/store/xl7vdrxipggh2v5v2w5002l3rmzajzvp-opam-nix-gen/bin/opam-nix-gen: line 21: package-defs.json: command not found
    Resolve a package called , the source of which is in the current directory, and write the defs to :
      opam-nix-gen my-package . package-defs.json
```

This is a minor issue, it seems that `my-package` and `package-defs.json` are [quoted](https://github.com/tweag/opam-nix/blob/8710fa3906023308c4528f990a09a69e894b0d1a/scripts/opam-nix-gen.in#L21) in the help output.

Running with all the required arguments:

```
$ nix shell github:tweag/opam-nix#opam-nix-gen --command opam-nix-gen my-project . package-defs.json
/nix/store/xl7vdrxipggh2v5v2w5002l3rmzajzvp-opam-nix-gen/bin/opam-nix-gen: line 85: realpath: command not found
```

Is there something wrong with my environment?

**Comment by balsoft** [comment]
Sorry, yeah, now `opam-nix-gen` adds all the dependencies it needs to `PATH`.

**Comment by rizo** [comment]
@balsoft thanks for fixing those! I was able to generate the `package-defs.json` file, but unfortunately the build did not work.

From my observations there's an issue with depext resolution and patching when building from the lock file.

Here's a detailed log and project files I used to test this: https://gist.github.com/rizo/2f484b83acf7d295f69ba748e7ffb3c2

Let me know if I'm doing something wrong.

**Comment by balsoft** [comment]
Oh, this is just an issue with an overlay in opam-nix :) It applies nixpkgs patches to `ocamlfind`, but those patches don't apply with `1.9.3` anymore. I'll fix this.

**Comment by balsoft** [comment]
Should be fixed now.

**Comment by rizo** [comment]
Thanks, @balsoft! Will test the latest changes. I'm still seeing the following warning by the way:

```
trace: warning: dream: missing dep: conf-libev
```

**Comment by balsoft** [comment]
> trace: warning: dream: missing dep: conf-libev

This is because for whatever reason `opam admin list --resolve` didn't include the `conf-libev` in the list of resolved packages.

**Comment by balsoft** [comment]
Could you confirm that this is resolved now?

**Comment by rizo** [comment]
Yes, I just tested latest changes in my project and everything seems to work!

Thanks @balsoft
